afnd.set_alfabeto(['0','1'])
afnd.set_estados(['q1','q2','q3'])
afnd.set_estadoInicial('q1')
afnd.set_estadosFinais(['q2'])
afnd.set_transicoes({'q1':{'0':['q3'],'1':['q1']},'q2':{'0':['q3','q2'],'1':['q3']},'q3':{'0':['q1'],'1':['q2']}}) 